### ISSUE TITLE
Cannot access query on a page with prerendering enabled

### ISSUE THREAD

**Issue by spences10** [mattjennings/sveltekit-blog-template#1]
Hey Matt!

I'm putting together a guide on adding an RSS feed using this template as reference and there's an error after installing dependencies and running the dev server.

Turning off the `  export const prerender = true` flag in `src/routes.svelte` resolves this.

I can make a PR for it if you like?

**Comment by mattjennings** [comment]
What's the error that happens? The only thing I'd want to make sure is that it doesn't break SSG for that page - however, the static adapter will prerender regardless, so if the build ultimately works then that's probably all that matters.

**Comment by mattjennings** [comment]
Removed query usage in the template, so this should be good now
