### ISSUE TITLE
Table of content

### ISSUE THREAD

**Issue by adi-dev-1337** [mattjennings/sveltekit-blog-template#11]
Everything that isn't Chrome renders the table of content in a post to further offscreen to the right, visible only with a zoom out

**Comment by mattjennings** [comment]
Sorry, I missed this but I'm not able to reproduce it on Safari or FireFox. Looks normal to me on both browsers. 

I'll close for now, but if you can provide a screenshot of the issue with a specific browser version I'll reopen and take a look.
