### ISSUE TITLE
Better line breaks

### ISSUE THREAD

**Issue by Ak4zh** [mattjennings/sveltekit-blog-template#14]
One annoying thing with markdown is if you add a single line break gets removed in the final output.
Double line breaks (double return) creates a bigger gap.

The solution is to us `<br>` html break tag.
Is it possible to update this template parse single line breaks automatically to `<br>` tag.

**Comment by mattjennings** [comment]
That is the expected behaviour of markdown and I do not wish to change that. Double line breaks results in a new paragraph, ie a <p> tag, so you could adjust the size of the gaps through css or the tailwind config if you find them too big.
