### ISSUE TITLE
Rendering preview.html

### ISSUE THREAD

**Issue by WesselvanDam** [mattjennings/sveltekit-blog-template#20]
The PostPreview shows a preview of a post's body using the `post.preview` tag, see [here](https://github.com/mattjennings/sveltekit-blog-template/blob/b035ac11861bfeb73363f5a78cb70d14ff7878f9/src/lib/components/PostPreview.svelte#L12). This works fine when the markdown file does **not** specify a preview text (as the example posts do), as then the first `<p>` element is used (see [here](https://github.com/mattjennings/sveltekit-blog-template/blob/b035ac11861bfeb73363f5a78cb70d14ff7878f9/src/lib/data/posts.js#L15), but for me it does not work when a preview text **is** specified, as [this line](https://github.com/mattjennings/sveltekit-blog-template/blob/b035ac11861bfeb73363f5a78cb70d14ff7878f9/src/lib/data/posts.js#L40) stringifies the preview. Thus, for me using asterisks for bold ends up shown as `**this**`. How can I correctly render the preview markdown?

**Comment by mattjennings** [comment]
Hm, yeah, that was a feature added [here](https://github.com/mattjennings/sveltekit-blog-template/pull/7). Seems we never considered parsing that text as markdown.

You could [manually run remark](https://github.com/remarkjs/remark#examples) (or some markdown formatter) on the preview metadata in `posts.js`, and pass that down instead.

**Comment by WesselvanDam** [comment]
No problem, thanks for the explanation!
