### ISSUE TITLE
Typescript rewrite

### ISSUE THREAD

**Issue by baseplate-admin** [mattjennings/sveltekit-blog-template#24]
Hi,

Thanks for creating this awesome  package. I was wondering if it was possible to recreate this package using typescript?

**Comment by mattjennings** [comment]
I purposefully wrote it in JS so that it didn't require knowing TS to use this template. It isn't too much work to convert the JS portions into TS for those that want it (whereas the opposite is not true).

**Comment by baseplate-admin** [comment]
Fair enough. Have a good day :D
