### ISSUE TITLE
Can you clarify how you want this code to be used by providing a license please ?

### ISSUE THREAD

**Issue by ymolists** [mattjennings/sveltekit-blog-template#8]
Hi @mattjennings 

Thank you so much for providing this demo.

I was not sure what you consider to be fair use when copying the code in this repo so i felt i should ask permissions (and license clarifications) as opposed to copy and pasting :-) 

Best Regards

**Comment by mattjennings** [comment]
Hey @ymolists, thanks for bringing this up! Definitely feel free to use anything in this repo in any way you wish, but I will add a license that states the same for something more formal.

**Comment by mattjennings** [comment]
MIT license is now included
